### ISSUE TITLE
Fails to install to a file path with spaces in it

### ISSUE THREAD

**Issue by danielbayley** [Microsoft/node-pty#129]
This is a dependency of _[atom-terminal-tab]_, but that package fails to install, throwing an error from this module's `package.json`.`scripts`.[`install`] lifecycle script.

Since I am on macOS, my `ATOM_HOME` is set to `~/Library/Application Support/Atom`, making the install path `~/Library/Application Support/Atom/packages/atom-terminal-tab`, hence the space in the file path, which I'm certain is causing the `ELIFECYCLE` script error.

If I do `export ATOM_HOME=$HOME/.atom` beforehand, then the package (with this module as a dependency) install works as expected. But then I have to manually navigate to this temporary install setup and move the package over to the correct location and cleanup the rest. Obviously this also messes up auto-update of packages.

Regardless, it should be more robust to file paths with spaces in…

Here is the stack trace:
~~~ sh
apm i atom-terminal-tab
Installing atom-terminal-tab to /Users/Dan/Library/Application Support/Atom/packages ✗

> node-pty@0.6.10 install /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117630-28249-1mi5mq2.vl299ysyvi/node_modules/atom-terminal-tab/node_modules/node-pty
> node scripts/install.js

  CXX(target) Release/obj.target/pty/src/unix/pty.o
/private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117630-28249-1mi5mq2.vl299ysyvi
└── (empty)


2017-07-30 16:54:38.078 xcodebuild[28264:2742256] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-07-30 16:54:38.082 xcodebuild[28264:2742256] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
clang: error: no such file or directory: 'Support/Atom/.node-gyp/.node-gyp/iojs-1.6.9/include/node'
clang: error: no such file or directory: 'Support/Atom/.node-gyp/.node-gyp/iojs-1.6.9/src'
clang: error: no such file or directory: 'Support/Atom/.node-gyp/.node-gyp/iojs-1.6.9/deps/uv/include'
clang: error: no such file or directory: 'Support/Atom/.node-gyp/.node-gyp/iojs-1.6.9/deps/v8/include'
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117630-28249-1mi5mq2.vl299ysyvi/node_modules/atom-terminal-tab/node_modules/node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117630-28249-1mi5mq2.vl299ysyvi/package.json'
npm WARN apm-install-dir-117630-28249-1mi5mq2.vl299ysyvi No description
npm WARN apm-install-dir-117630-28249-1mi5mq2.vl299ysyvi No repository field.
npm WARN apm-install-dir-117630-28249-1mi5mq2.vl299ysyvi No README data
npm WARN apm-install-dir-117630-28249-1mi5mq2.vl299ysyvi No license field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Dan/Library/Application Support/Atom/.apm/.apmrc" "--userconfig" "/Users/Dan/Library/Application Support/Atom/.apmrc" "install" "/private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/d-117630-28249-72o0g.yfaxxbt9/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.6.10 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.6.10 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117630-28249-1mi5mq2.vl299ysyvi/npm-debug.log
npm ERR! code 1
~~~

[atom-terminal-tab]: https://github.com/jsmecham/atom-terminal-tab
[`install`]: https://github.com/Tyriar/node-pty/blob/master/package.json#L37

**Comment by Tyriar** [comment]
Hmm, clone and install definitely works for me:

```
~/playground
❯ mkdir "dir with space"

~/playground
❯ cd dir\ with\ space/

~/playground/dir with space
❯ ls

~/playground/dir with space
❯ git clone https://github.com/Tyriar/node-pty
Cloning into 'node-pty'...
remote: Counting objects: 3364, done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 3364 (delta 97), reused 120 (delta 61), pack-reused 3201
Receiving objects: 100% (3364/3364), 3.04 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1671/1671), done.

~/playground/dir with space
❯ cd node-pty/

~/playground/dir with space/node-pty @master
❯ npm i

> node-pty@0.6.10 install /Users/daimms/playground/dir with space/node-pty
> node scripts/install.js

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> node-pty@0.6.10 postinstall /Users/daimms/playground/dir with space/node-pty
> node scripts/post-install.js


> node-pty@0.6.10 prepublish /Users/daimms/playground/dir with space/node-pty
> npm run tsc


> node-pty@0.6.10 tsc /Users/daimms/playground/dir with space/node-pty
> tsc

node-pty@0.6.10 /Users/daimms/playground/dir with space/node-pty
├── @types/mocha@2.2.41
├── @types/node@6.0.85
...
```

Saving as a dependency also installs fine:

```
~/playground/dir with space/temp
❯ npm i -S node-pty

> node-pty@0.6.10 install /Users/daimms/playground/dir with space/temp/node_modules/node-pty
> node scripts/install.js

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> node-pty@0.6.10 postinstall /Users/daimms/playground/dir with space/temp/node_modules/node-pty
> node scripts/post-install.js

temp@1.0.0 /Users/daimms/playground/dir with space/temp
└─┬ node-pty@0.6.10
  └── nan@2.5.0

npm WARN temp@1.0.0 No description
npm WARN temp@1.0.0 No repository field.
```

Perhaps your xcode or apm setup is causing it somehow?
