### ISSUE TITLE
Fails to install on System Linux 2.6.32-431.23.3.el6.x86_64

### ISSUE THREAD

**Issue by zhengtulymGh** [Microsoft/node-pty#204]
## Environment details

- OS: Linux
- OS version: 2.6.32-431.23.3.el6.x86_64
- node-pty version: 0.7.2

## Issue description

```
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.jenkins/workspace/AutoDeploy/Node_Pty/server/node_modules/node-pty/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.9.5/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.9.5',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/.jenkins/workspace/AutoDeploy/Node_Pty/server/node_modules/node-pty',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/root/.jenkins/workspace/AutoDeploy/Node_Pty/server/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:47:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/.node-gyp/6.9.5/include/node/node.h:42,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/6.9.5/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.9.5/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/6.9.5/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/6.9.5/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/6.9.5/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/6.9.5/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: At global scope:
/root/.node-gyp/6.9.5/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.9.5/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/6.9.5/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/6.9.5/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/6.9.5/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: At global scope:
/root/.node-gyp/6.9.5/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.9.5/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/6.9.5/include/node/v8.h:3277: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: At global scope:
/root/.node-gyp/6.9.5/include/node/v8.h:4497: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h:4513: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.9.5/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/6.9.5/include/node/v8.h:7537: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:197,
                 from ../src/unix/pty.cc:20:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:29: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:37: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:45: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:52: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:71: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:79: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:87: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:96: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:109: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:130: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:147: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:157: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:173: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:181: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:187: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:196: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:203: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:211: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:226: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:234: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:242: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:250: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:258: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:266: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:276: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:286: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:298: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:309: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:316: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:322: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:328: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:334: error: expected initializer before ‘<’ token
../src/unix/pty.cc:717: error: expected ‘}’ at end of input
../../nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
make: Leaving directory `/root/.jenkins/workspace/AutoDeploy/Node_Pty/server/node_modules/node-pty/build'
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-431.23.3.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.jenkins/workspace/AutoDeploy/Node_Pty/server/node_modules/node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by Tyriar** [comment]
> ../../nan/nan.h:47:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
