### ISSUE TITLE
ioctl(2) failed exception

### ISSUE THREAD

**Issue by Tyriar** [microsoft/node-pty#220]
Maybe the pty has already been destroyed?

```
Stack 
Error: ioctl(2) failed.
at UnixTerminal.resize (/node_modules.asar/node-pty/lib/unixTerminal.js:227:13)
/vs/workbench/parts/terminal/node/terminalProcess.ts#123:19 (resize)
/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#158:17 (setDimensions)
/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#999:72 (onComplete)
/vs/base/common/winjs.base.js#1191:0 (_notify)
/vs/base/common/winjs.base.js#867:0 (enter)
/vs/base/common/winjs.base.js#1089:0 (_run)
/vs/base/common/winjs.base.js#1057:0 (c)
/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#63:4 (call)
/vs/base/common/event.ts#140:15 (fire)
/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#132:24 (call)
/vs/base/common/event.ts#140:15 (fire)
/vs/workbench/parts/terminal/node/terminalProcess.ts#104:25 (_sendProcessId)
/vs/workbench/parts/terminal/node/terminalProcess.ts#69:8
```

VS Code issue: https://github.com/Microsoft/vscode/issues/57976

**Comment by jerch** [comment]
@Tyriar:
Hard to say, this error will be thrown whenever the file descriptor `fd` is invalid: https://github.com/Microsoft/node-pty/blob/1c3cd4710c48ad45615da562d10d76162ad43c39/src/unix/pty.cc#L368

Possible reasons:
- fd is something else (not a pty master at all)
- pty already closed and fd is stale
- fd number got reattched to something else (e.g. some other file)

Any more info when this exactly happens?

Might be useful to output `errno` to see the actual error.

**Comment by Tyriar** [comment]
No more info unfortunately, these are just errors that we're seeing in the wild.

**Comment by Tyriar** [comment]
I don't see how this could happen atm as this._fd is synchronously in the ctor and resize must have been called after it, but the repro in https://github.com/Microsoft/vscode/issues/71078 seems to indicate that resizing again will fix it.

**Comment by Tyriar** [comment]
Adding a better error that should reveal why the call failed in https://github.com/Microsoft/node-pty/pull/285

**Comment by Tyriar** [comment]
Experience on Windows/conpty:

```
> const a = require('.')
undefined
> const b = a.spawn('cmd.exe')
undefined
> b.resize(10, 10)
undefined
> b.kill()
undefined
> b.resize(10, 10)
Uncaught Error: Cannot resize a pty that has already exited
    at WindowsPtyAgent.resize (C:\Github\microsoft\node-pty\lib\windowsPtyAgent.js:121:23)
    at WindowsTerminal.<anonymous> (C:\Github\microsoft\node-pty\lib\windowsTerminal.js:130:26)
    at WindowsTerminal._deferNoArgs (C:\Github\microsoft\node-pty\lib\windowsTerminal.js:161:24)
    at WindowsTerminal.resize (C:\Github\microsoft\node-pty\lib\windowsTerminal.js:129:14)
```

https://github.com/microsoft/node-pty/blob/8305f06b6a2601209fd40e9fe0647cc10cbbdf26/src/windowsPtyAgent.ts#L126-L128

**Comment by Tyriar** [comment]
mac:

```
> b.resize(10, 10)
Uncaught Error: ioctl(2) failed, EBADF
    at UnixTerminal.resize (/Users/tyriar/dev/microsoft/node-pty/lib/unixTerminal.js:253:13)
```

We pass through the error here:

https://github.com/microsoft/node-pty/blob/d2d8fd39a569ad8c7a443040b02ea1d5ebad4559/src/unix/pty.cc#L522-L534

This is good enough for now as it's easy to look up what the error means.
