### ISSUE TITLE
Syntax error in install.js

### ISSUE THREAD

**Issue by aggsol** [microsoft/node-pty#300]
```
/home/user/lib/node_modules/wetty.js/node_modules/node-pty/scripts/install.js:3
const os = require('os');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

- Linux 2.6.32-754.14.2.el6.x86_64
- argv "node" "/home/user/bin/npm" "i" "-g" "wetty.js"
- node v0.10.43
- npm  v2.15.12

```
node-pty@0.7.8 install: `node scripts/install.js`
Exit status 8

Failed at the node-pty@0.7.8 install script 'node scripts/install.js'.
This is most likely a problem with the node-pty package,
not with npm itself.
Tell the author that this fails on your system:
    node scripts/install.js
```

**Comment by Tyriar** [comment]
Don't use node 0.10 is the fix, node-pty only really targets 10+ at this point.
