### ISSUE TITLE
node-pty builds error on nodejs v12.3.0

### ISSUE THREAD

**Issue by hieuhlc** [microsoft/node-pty#303]
## Environment details

- OS: MacOS, Ubuntu & Windows (azure pipeline hosted agent)
- OS version:
- node-pty version: 0.9.0-alpha4

## Issue description
I'm building app using Electron v5.0.1 and Nodejs 12.3.0. Logs of error:
```
[5/5] Building fresh packages...
error /Users/vsts/agent/2.150.3/work/1/s/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /Users/vsts/agent/2.150.3/work/1/s/node_modules/node-pty
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.3.0 | darwin | x64
gyp http GET https://nodejs.org/download/release/v12.3.0/node-v12.3.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.3.0/node-v12.3.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.3.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.3.0/SHASUMS256.txt
gyp info spawn /usr/local/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/vsts/agent/2.150.3/work/1/s/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/vsts/agent/2.150.3/work/1/s/node_modules/node-pty/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/vsts/agent/2.150.3/work/1/s/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/vsts/.node-gyp/12.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/vsts/.node-gyp/12.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/vsts/agent/2.150.3/work/1/s/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/vsts/.node-gyp/12.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/vsts/agent/2.150.3/work/1/s/node_modules/node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:53:
/Users/vsts/.node-gyp/12.3.0/include/node/node.h:107:12: fatal error: 'util-inl.h' file not found
#  include <util-inl.h>
           ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/vsts/agent/2.150.3/work/1/s/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/vsts/hostedtoolcache/node/12.3.0/x64/bin/node" "/Users/vsts/agent/2.150.3/work/1/s/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/vsts/agent/2.150.3/work/1/s/node_modules/node-pty
gyp ERR! node -v v12.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by Tyriar** [comment]
https://github.com/microsoft/node-pty/issues/279

**Comment by Tyriar** [comment]
Ugh, just realized those alpha builds were published under latest, I'll fix that up. 0.8.1 is the latest (but it will doesn't work on node 12 until the next release)
