### ISSUE TITLE
Error creating winpty: ConnectNamedPipe failed: Windows error 232

### ISSUE THREAD

**Issue by cobidennis** [microsoft/node-pty#344]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version:

## Issue description
Error creating winpty: ConnectNamedPipe failed: Windows error 232

I encountered this error after my OS updated today
I open an instance of Git Bash and ran
`php artisan serve`
 The error pop up and a similar error is happening from my PHPStorm IDE terminal which is show the following error:
Cannot open Local Terminal
Failed to start [cmd.exe] in C:/User/me/repo/project1

##PHPStorm Log
2019-08-16 11:26:43,608 [2742117]   INFO - erminal.AbstractTerminalRunner - Cannot open Local Terminal 
java.util.concurrent.ExecutionException: Failed to start [cmd.exe] in C:/Users/denis.obi/repo/iconnex-laravel/CLM-33
	at org.jetbrains.plugins.terminal.LocalTerminalDirectRunner.createProcess(LocalTerminalDirectRunner.java:211)
	at org.jetbrains.plugins.terminal.LocalTerminalDirectRunner.createProcess(LocalTerminalDirectRunner.java:58)
	at org.jetbrains.plugins.terminal.AbstractTerminalRunner.lambda$openSessionInDirectory$4(AbstractTerminalRunner.java:208)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Couldn't create PTY
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:75)
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:50)
	at com.pty4j.PtyProcessBuilder.start(PtyProcessBuilder.java:109)
	at com.pty4j.PtyProcess.exec(PtyProcess.java:78)
	at com.pty4j.PtyProcess.exec(PtyProcess.java:49)
	at org.jetbrains.plugins.terminal.LocalTerminalDirectRunner.lambda$createProcess$0(LocalTerminalDirectRunner.java:202)
	at org.jetbrains.plugins.terminal.TerminalSignalUtil.computeWithIgnoredSignalsResetToDefault(TerminalSignalUtil.java:41)
	at org.jetbrains.plugins.terminal.LocalTerminalDirectRunner.createProcess(LocalTerminalDirectRunner.java:200)
	... 8 more
Caused by: com.pty4j.PtyException: Error starting winpty: ConnectNamedPipe failed: Windows error 232
	at com.pty4j.windows.WinPty.<init>(WinPty.java:91)
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:72)
	... 15 more

**Comment by Tyriar** [comment]
This typically happens when anti virus blocks winpty from doing its thing

**Comment by cobidennis** [comment]
I don't have any third-party anti virus program installed.
Could it be Windows Defender....
and why does it happen both on git bash and PHPStorm terminal

**Comment by Tyriar** [comment]
Something on your system is blocking winpty from doing its thing, you will have to figure it out yourself. We've stopped servicing winpty issues as conpty is the focus now (supported in Windows 10 1903+)
