### ISSUE TITLE
Installation Error : make: *** [pty.target.mk:105: Release/obj.target/pty/src/unix/pty.o] Error 1

### ISSUE THREAD

**Issue by VineshReddy** [microsoft/node-pty#361]
## Environment details

- OS: archlinux
- OS version: Linux 4.19.80-1-lts
- node-pty version: 0.8.1

## Issue description
**Unable to install with npm, yarn**

npm i -g node-pty

```
../node_modules/nan/nan_object_wrap.h:66:61:   required from here
/home/vinesh/.cache/node-gyp/12.12.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [pty.target.mk:105: Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory '/home/vinesh/Applications/.npm/lib/node_modules/node-pty/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.80-1-lts
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vinesh/Applications/.npm/lib/node_modules/node-pty
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.8.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vinesh/.npm/_logs/2019-10-22T03_25_49_625Z-debug.log

```
**Log file** : /home/vinesh/.npm/_logs/2019-10-22T03_25_49_625Z-debug.log
```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'node-pty' ]
2 info using npm@6.12.0
3 info using node@v12.12.0
4 verbose npm-session 7d8b5bc1076f176d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/node-pty 442ms (from cache)
8 silly pacote tag manifest for node-pty@latest fetched in 456ms
9 timing stage:loadCurrentTree Completed in 491ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-pty@0.8.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/nan 101ms (from cache)
18 silly pacote version manifest for nan@2.12.1 fetched in 103ms
19 silly resolveWithNewModule nan@2.12.1 checking installable status
20 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 108ms
21 timing stage:loadIdealTree Completed in 112ms
22 silly currentTree lib
23 silly idealTree lib
23 silly idealTree └─┬ node-pty@0.8.1
23 silly idealTree   └── nan@2.12.1
24 silly install generateActionsToTake
25 timing stage:generateActionsToTake Completed in 4ms
26 silly diffTrees action count 2
27 silly diffTrees add nan@2.12.1
28 silly diffTrees add node-pty@0.8.1
29 silly decomposeActions action count 16
30 silly decomposeActions fetch nan@2.12.1
31 silly decomposeActions extract nan@2.12.1
32 silly decomposeActions preinstall nan@2.12.1
33 silly decomposeActions build nan@2.12.1
34 silly decomposeActions install nan@2.12.1
35 silly decomposeActions postinstall nan@2.12.1
36 silly decomposeActions finalize nan@2.12.1
37 silly decomposeActions refresh-package-json nan@2.12.1
38 silly decomposeActions fetch node-pty@0.8.1
39 silly decomposeActions extract node-pty@0.8.1
40 silly decomposeActions preinstall node-pty@0.8.1
41 silly decomposeActions build node-pty@0.8.1
42 silly decomposeActions install node-pty@0.8.1
43 silly decomposeActions postinstall node-pty@0.8.1
44 silly decomposeActions finalize node-pty@0.8.1
45 silly decomposeActions refresh-package-json node-pty@0.8.1
46 silly install executeActions
47 silly doSerial global-install 16
48 verbose correctMkdir /home/vinesh/.npm/_locks correctMkdir not in flight; initializing
49 verbose lock using /home/vinesh/.npm/_locks/staging-6f5ab3b622f16e83.lock for /home/vinesh/Applications/.npm/lib/node_modules/.staging
50 silly doParallel extract 2
51 silly extract nan@2.12.1
52 silly extract node-pty@0.8.1
53 silly tarball trying nan@2.12.1 by hash: sha512-JY7V6lRkStKcKTvHO5NVSQRv+RV+FIL5pvDoLiAtSL9pKlC5x9PKQcZDsq7m4FO4d57mkhC6Z+QhAh3Jdk5JFw==
54 silly tarball trying node-pty@latest by hash: sha512-j+/g0Q5dR+vkELclpJpz32HcS3O/3EdPSGPvDXJZVJQLCvgG0toEbfmymxAEyQyZEpaoKHAcoL+PvKM+4N9nlw==
55 silly extract nan@2.12.1 extracted to /home/vinesh/Applications/.npm/lib/node_modules/.staging/nan-8b79da8d (66ms)
56 silly extract node-pty@latest extracted to /home/vinesh/Applications/.npm/lib/node_modules/.staging/node-pty-fb6a326f (108ms)
57 timing action:extract Completed in 110ms
58 silly doReverseSerial unbuild 16
59 silly doSerial remove 16
60 silly doSerial move 16
61 silly doSerial finalize 16
62 silly finalize /home/vinesh/Applications/.npm/lib/node_modules/node-pty/node_modules/nan
63 silly finalize /home/vinesh/Applications/.npm/lib/node_modules/node-pty
64 timing action:finalize Completed in 7ms
65 silly doParallel refresh-package-json 2
66 silly refresh-package-json /home/vinesh/Applications/.npm/lib/node_modules/node-pty/node_modules/nan
67 silly refresh-package-json /home/vinesh/Applications/.npm/lib/node_modules/node-pty
68 timing action:refresh-package-json Completed in 16ms
69 silly doParallel preinstall 2
70 silly preinstall nan@2.12.1
71 info lifecycle nan@2.12.1~preinstall: nan@2.12.1
72 silly preinstall node-pty@0.8.1
73 info lifecycle node-pty@0.8.1~preinstall: node-pty@0.8.1
74 timing action:preinstall Completed in 2ms
75 silly doSerial build 16
76 silly build nan@2.12.1
77 info linkStuff nan@2.12.1
78 silly linkStuff nan@2.12.1 has /home/vinesh/Applications/.npm/lib/node_modules/node-pty/node_modules as its parent node_modules
79 silly linkStuff nan@2.12.1 is part of a global install
80 silly linkStuff nan@2.12.1 is installed into a global node_modules
81 silly build node-pty@0.8.1
82 info linkStuff node-pty@0.8.1
83 silly linkStuff node-pty@0.8.1 has /home/vinesh/Applications/.npm/lib/node_modules as its parent node_modules
84 silly linkStuff node-pty@0.8.1 is part of a global install
85 silly linkStuff node-pty@0.8.1 is installed into a global node_modules
86 silly linkStuff node-pty@0.8.1 is installed into the top-level global node_modules
87 timing action:build Completed in 2ms
88 silly doSerial global-link 16
89 silly doParallel update-linked 0
90 silly doSerial install 16
91 silly install nan@2.12.1
92 info lifecycle nan@2.12.1~install: nan@2.12.1
93 silly install node-pty@0.8.1
94 info lifecycle node-pty@0.8.1~install: node-pty@0.8.1
95 verbose lifecycle node-pty@0.8.1~install: unsafe-perm in lifecycle true
96 verbose lifecycle node-pty@0.8.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vinesh/Applications/.npm/lib/node_modules/node-pty/node_modules/.bin:/home/vinesh/Applications/.npm/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/vinesh/Applications/.npm/bin/:/home/vinesh/Applications/bin/:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/vinesh/Applications/.npm/bin/:/home/vinesh/Applications/bin/
97 verbose lifecycle node-pty@0.8.1~install: CWD: /home/vinesh/Applications/.npm/lib/node_modules/node-pty
98 silly lifecycle node-pty@0.8.1~install: Args: [ '-c', 'node scripts/install.js' ]
99 silly lifecycle node-pty@0.8.1~install: Returned: code: 1  signal: null
100 info lifecycle node-pty@0.8.1~install: Failed to exec install script
101 timing action:install Completed in 1206ms
102 verbose unlock done using /home/vinesh/.npm/_locks/staging-6f5ab3b622f16e83.lock for /home/vinesh/Applications/.npm/lib/node_modules/.staging
103 timing stage:rollbackFailedOptional Completed in 44ms
104 timing stage:runTopLevelLifecycles Completed in 2002ms
105 verbose stack Error: node-pty@0.8.1 install: `node scripts/install.js`
105 verbose stack Exit status 1
105 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
105 verbose stack     at EventEmitter.emit (events.js:210:5)
105 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
105 verbose stack     at ChildProcess.emit (events.js:210:5)
105 verbose stack     at maybeClose (internal/child_process.js:1021:16)
105 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
106 verbose pkgid node-pty@0.8.1
107 verbose cwd /home/vinesh
108 verbose Linux 4.19.80-1-lts
109 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "node-pty"
110 verbose node v12.12.0
111 verbose npm  v6.12.0
112 error code ELIFECYCLE
113 error errno 1
114 error node-pty@0.8.1 install: `node scripts/install.js`
114 error Exit status 1
115 error Failed at the node-pty@0.8.1 install script.
115 error This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by Tyriar** [comment]
Not sure what the issue is here, the only thing that looks off is that you're installing the module globally?

**Comment by VineshReddy** [comment]
Yes my installation failed for 0.8.1 even from tarball, 0.8.1 doesn't seem to work for me , beta version installs and works fine.
`npm i -g node-pty@0.9.0-beta28`
