### ISSUE TITLE
Problems installing node-pty on production Linux Red Hat server

### ISSUE THREAD

**Issue by ZeldOcarina** [microsoft/node-pty#370]
Hello!

I am trying to install sharp into a production VPS with pm2 but it won't install and I get a 404 on NGINX.

This is my log:

```
> node-pty@0.9.0 install /home/Mattia/casalugano-test/node_modules/node-pty
> node scripts/install.js

make: Entering directory `/home/Mattia/casalugano-test/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: execvp: g++: Permission denied
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
make: Leaving directory `/home/Mattia/casalugano-test/node_modules/node-pty/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-862.11.6.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/Mattia/casalugano-test/node_modules/node-pty
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

> sharp@0.23.3 install /home/Mattia/casalugano-test/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/Mattia/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
npm WARN multer-sharp-s3@0.1.0 requires a peer of sharp@>=0.170 <= 0.20.8 but none is installed. You must install peer dependencies yourself.
npm WARN casa-lugano@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/ndb/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-pty@0.9.0 (node_modules/node-pty):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-pty@0.9.0 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ sharp@0.23.3
updated 1 package and audited 11752 packages in 9.038s
found 0 vulnerabilities
Node Version: 10.17.0
npm Version: 6.11.3
```

I have tried everything, it works smoothly on localhost of my machine, I can install and coded the features needed but now it crashes my production server and I've had to revert to previous version to get the app back up.

Any suggestions?

**Comment by Tyriar** [comment]
> make: execvp: g++: Permission denied

Looks like you need to tweak some permissions to fix this error

**Comment by ZeldOcarina** [comment]
Thanks for your comment but I'm getting errors on Heroku as well, it's not a permissions problem!

```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.13.1...
       Using default npm version: 6.12.1
       
-----> Restoring cache
       - node_modules
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       
       > node-pty@0.9.0-beta9 install /tmp/build_90e4472da05af926b55c1eaf2fb0f900/node_modules/node-pty
       > node scripts/install.js
       
       make: Entering directory '/tmp/build_90e4472da05af926b55c1eaf2fb0f900/node_modules/node-pty/build'
         CXX(target) Release/obj.target/pty/src/unix/pty.o
       ../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/unix/pty.cc:195:53: warning: ‘v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const’ is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
          if (info[8]->BooleanValue(Nan::GetCurrentContext()).FromJust()) {
                                                            ^
       In file included from /app/.cache/node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                        from /app/.cache/node-gyp/12.13.1/include/node/v8.h:25,
                        from /app/.cache/node-gyp/12.13.1/include/node/node.h:63,
                        from ../../nan/nan.h:54,
                        from ../src/unix/pty.cc:20:
       /app/.cache/node-gyp/12.13.1/include/node/v8.h:2606:51: note: declared here
                        V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                          ^
       /app/.cache/node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       ../src/unix/pty.cc: In function ‘void pty_after_waitpid(uv_async_t*)’:
       ../src/unix/pty.cc:495:69: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
          Nan::Callback(cb).Call(Nan::GetCurrentContext()->Global(), 2, argv);
                                                                            ^
       In file included from ../src/unix/pty.cc:20:0:
       ../../nan/nan.h:1718:3: note: declared here
          Call(v8::Local<v8::Object> target
          ^~~~
         SOLINK_MODULE(target) Release/obj.target/pty.node
         COPY Release/pty.node
       make: Leaving directory '/tmp/build_90e4472da05af926b55c1eaf2fb0f900/node_modules/node-pty/build'
       
       > sharp@0.20.8 install /tmp/build_90e4472da05af926b55c1eaf2fb0f900/node_modules/multer-sharp-s3/node_modules/sharp
       > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
       
       info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz
       make: Entering directory '/tmp/build_90e4472da05af926b55c1eaf2fb0f900/node_modules/multer-sharp-s3/node_modules/sharp/build'
         TOUCH Release/obj.target/libvips-cpp.stamp
         CXX(target) Release/obj.target/sharp/src/common.o
       In file included from ../src/common.cc:27:0:
       ../src/common.h:82:20: error: ‘Handle’ is not a member of ‘v8’
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                           ^~~~~~
       ../src/common.h:82:37: error: expected primary-expression before ‘>’ token
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                            ^
       ../src/common.h:82:39: error: ‘obj’ was not declared in this scope
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                              ^~~
       ../src/common.h:82:56: error: expected primary-expression before ‘attr’
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                                               ^~~~
       ../src/common.h:82:60: error: expression list treated as compound expression in initializer [-fpermissive]
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                                                   ^
       ../src/common.h:83:29: error: ‘Handle’ is not a member of ‘v8’
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                    ^~~~~~
       ../src/common.h:83:46: error: expected primary-expression before ‘>’ token
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                                     ^
       ../src/common.h:83:48: error: ‘obj’ was not declared in this scope
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                                       ^~~
       ../src/common.h:83:65: error: expected primary-expression before ‘attr’
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                                                        ^~~~
       ../src/common.h:84:48: error: ‘Handle’ is not a member of ‘v8’
          template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                       ^~~~~~
       ../src/common.h:84:65: error: expected primary-expression before ‘>’ token
          template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                        ^
       ../src/common.h:84:67: error: ‘obj’ was not declared in this scope
          template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                          ^~~
       ../src/common.h:84:84: error: expected primary-expression before ‘attr’
          template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                                           ^~~~
       ../src/common.h:84:37: warning: variable templates only available with -std=c++14 or -std=gnu++14
          template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                            ^~~~~~
       ../src/common.h:84:90: error: expected ‘;’ before ‘{’ token
          template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                                                 ^
       ../src/common.h:87:37: error: ‘Handle’ is not a member of ‘v8’
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                            ^~~~~~
       ../src/common.h:87:54: error: expected primary-expression before ‘>’ token
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                             ^
       ../src/common.h:87:56: error: ‘obj’ was not declared in this scope
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                               ^~~
       ../src/common.h:87:73: error: expected primary-expression before ‘attr’
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                                                ^~~~
       ../src/common.h:87:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                 ^~~~~~
       ../src/common.h:87:79: error: expected ‘;’ before ‘{’ token
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                                                      ^
       ../src/common.h:90:37: error: ‘Handle’ is not a member of ‘v8’
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                            ^~~~~~
       ../src/common.h:90:54: error: expected primary-expression before ‘>’ token
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                             ^
       ../src/common.h:90:56: error: ‘obj’ was not declared in this scope
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                               ^~~
       ../src/common.h:90:61: error: expected primary-expression before ‘int’
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                                    ^~~
       ../src/common.h:87:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                 ^~~~~~
       ../src/common.h:90:71: error: expected ‘;’ before ‘{’ token
          template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                                              ^
       ../src/common.h:96:9: error: ‘Handle’ is not a member of ‘v8’
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                ^~~~~~
       ../src/common.h:96:26: error: expected primary-expression before ‘>’ token
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                 ^
       ../src/common.h:96:28: error: ‘input’ was not declared in this scope
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                   ^~~~~
       ../src/common.h:96:28: note: suggested alternative: ‘ino_t’
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                   ^~~~~
                                   ino_t
       ../src/common.h:96:70: error: expected primary-expression before ‘&’ token
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                                                             ^
       ../src/common.h:96:71: error: ‘buffersToPersist’ was not declared in this scope
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                                                              ^~~~~~~~~~~~~~~~
       ../src/common.h:96:87: error: expression list treated as compound expression in initializer [-fpermissive]
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                                                                              ^
       ../src/common.cc:34:20: error: redefinition of ‘bool sharp::HasAttr’
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                           ^~~~~~
       In file included from ../src/common.cc:27:0:
       ../src/common.h:82:8: note: ‘bool sharp::HasAttr’ previously defined here
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
               ^~~~~~~
       ../src/common.cc:34:20: error: ‘Handle’ is not a member of ‘v8’
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                           ^~~~~~
       ../src/common.cc:34:37: error: expected primary-expression before ‘>’ token
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                                            ^
       ../src/common.cc:34:39: error: ‘obj’ was not declared in this scope
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                                              ^~~
       ../src/common.cc:34:56: error: expected primary-expression before ‘attr’
          bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                                                               ^~~~
       ../src/common.cc:37:29: error: redefinition of ‘std::string sharp::AttrAsStr’
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                    ^~~~~~
       In file included from ../src/common.cc:27:0:
       ../src/common.h:83:15: note: ‘std::string sharp::AttrAsStr’ previously declared here
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                      ^~~~~~~~~
       ../src/common.cc:37:29: error: ‘Handle’ is not a member of ‘v8’
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                    ^~~~~~
       ../src/common.cc:37:46: error: expected primary-expression before ‘>’ token
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                                     ^
       ../src/common.cc:37:48: error: ‘obj’ was not declared in this scope
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                                       ^~~
       ../src/common.cc:37:65: error: expected primary-expression before ‘attr’
          std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                                                        ^~~~
       ../src/common.cc:43:9: error: redefinition of ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                ^~~~~~
       In file included from ../src/common.cc:27:0:
       ../src/common.h:95:20: note: ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’ previously defined here
          InputDescriptor* CreateInputDescriptor(
                           ^~~~~~~~~~~~~~~~~~~~~
       ../src/common.cc:43:9: error: ‘Handle’ is not a member of ‘v8’
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                ^~~~~~
       ../src/common.cc:43:26: error: expected primary-expression before ‘>’ token
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                                 ^
       ../src/common.cc:43:28: error: ‘input’ was not declared in this scope
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                                   ^~~~~
       ../src/common.cc:43:28: note: suggested alternative: ‘ino_t’
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                                   ^~~~~
                                   ino_t
       ../src/common.cc:43:70: error: expected primary-expression before ‘&’ token
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                                                                             ^
       ../src/common.cc:43:71: error: ‘buffersToPersist’ was not declared in this scope
            v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                                                                              ^~~~~~~~~~~~~~~~
       sharp.target.mk:134: recipe for target 'Release/obj.target/sharp/src/common.o' failed
       make: *** [Release/obj.target/sharp/src/common.o] Error 1
       make: Leaving directory '/tmp/build_90e4472da05af926b55c1eaf2fb0f900/node_modules/multer-sharp-s3/node_modules/sharp/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_90e4472da05af926b55c1eaf2fb0f900/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
       gyp ERR! System Linux 4.4.0-1048-aws
       gyp ERR! command "/tmp/build_90e4472da05af926b55c1eaf2fb0f900/.heroku/node/bin/node" "/tmp/build_90e4472da05af926b55c1eaf2fb0f900/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_90e4472da05af926b55c1eaf2fb0f900/node_modules/multer-sharp-s3/node_modules/sharp
       gyp ERR! node -v v12.13.1
       gyp ERR! node-gyp -v v5.0.5
       gyp ERR! not ok 
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! sharp@0.20.8 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the sharp@0.20.8 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.giV6C/_logs/2019-11-28T14_34_49_731Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by Tyriar** [comment]
@ZeldOcarina for the Heroku case it looks like the wrong version of Node.JS is being used as things are missing from the v8 namespace.
