### ISSUE TITLE
node 12.3.0 + electron 7.1.6

### ISSUE THREAD

**Issue by skarl-api** [microsoft/node-pty#374]
`npm install node-pty
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:54:
/Users/a/Library/Caches/node-gyp/12.3.0/include/node/node.h:107:12: fatal error: 'util-inl.h' file not found
#  include <util-inl.h>
           ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/a/Documents/nodeAllProject/shitCode/node_modules/node-pty
gyp ERR! node -v v12.3.0`

**Comment by Tyriar** [comment]
Does it work if you move to node 12.8.1 to match Electron's version? https://electronjs.org/releases/stable#7.0.0
