### ISSUE TITLE
npm install does not actually build?  (i.e. npm install does not invoke node-gyp)

### ISSUE THREAD

**Issue by risacher** [microsoft/node-pty#376]
## Environment details

- OS: ubuntu linux
- OS version:18.04 LTS
- node-pty version: node-pty@0.9.0

## Issue description

did 'npm install' in a project with dependency "node-pty": ">= 0.9.0".  Install worked fine - no errors.   When I ran my project though, I got below errors, which I believe means that node-pty didn't actually build.  I was able to resolve by 'cd node_modules/node-pty; node-gyp configure; node-gyp build'

innerError { Error: Cannot find module '../build/Debug/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/magnus/node/ttyx/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
/home/magnus/node/ttyx/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: Cannot find module '../build/Release/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/magnus/node/ttyx/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
magnus@eagle:~/node/ttyx$ node --version

**Comment by risacher** [comment]
FWIW, I had similar problems with other node modules that required node-gyp configure/build.  Maybe it's an npm issue?  This was on a 2-day old install of ubuntu 18.04 LTS, so maybe just some sort of system shakedown thing.

**Comment by Tyriar** [comment]
You probably had errors when you ran npm install initially. Check the output of:

```
rm -rf node_modules/node-pty
npm i
```

**Comment by martijnmichel** [comment]
I have this same problem and running node-gyp build doesnt fix it...

```
warning  in ./node_modules/node-pty-prebuilt-multiarch/lib/windowsPtyAgent.js

Module not found: Error: Can't resolve '../build/Debug/conpty.node' in '/mnt/usb2tb/apps/nordvpn-electron/node_modules/node-pty-prebuilt-multiarch/lib'

 warning  in ./node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js

Module not found: Error: Can't resolve '../build/Debug/pty.node' in '/mnt/usb2tb/apps/nordvpn-electron/node_modules/node-pty-prebuilt-multiarch/lib'

 warning  in ./node_modules/node-pty-prebuilt-multiarch/lib/windowsPtyAgent.js

Module not found: Error: Can't resolve '../build/Debug/pty.node' in '/mnt/usb2tb/apps/nordvpn-electron/node_modules/node-pty-prebuilt-multiarch/lib'

 warning  in ./node_modules/node-pty-prebuilt-multiarch/lib/windowsPtyAgent.js

Module not found: Error: Can't resolve '../build/Release/conpty.node' in '/mnt/usb2tb/apps/nordvpn-electron/node_modules/node-pty-prebuilt-multiarch/lib'

```

**Comment by martijnmichel** [comment]
I've just tried it on my macbook pro and it gives the same errors as i posted above.
Although I forgot to post these: (which also occurs above these earlier warnings on both OSes)

```
webpack-internal:///./node_modules/node-pty/lib/unixTerminal.js:33 innerError Error: Cannot find module '../build/Debug/pty.node'
    at webpackMissingModule (webpack-internal:///./node_modules/node-pty/lib/unixTerminal.js:30)
    at eval (webpack-internal:///./node_modules/node-pty/lib/unixTerminal.js:30)
    at Object../node_modules/node-pty/lib/unixTerminal.js (vendor.js:2436)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (webpack-internal:///./node_modules/node-pty/lib/index.js:13)
    at Object../node_modules/node-pty/lib/index.js (vendor.js:2412)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (webpack-internal:///./node_modules/babel-loader/lib/index.js?!./node_modules/@quasar/app/lib/webpack/loader.auto-import.js?kebab!./node_modules/vue-loader/lib/index.js?!./src/pages/Index.vue?vue&type=script&lang=js&:42)
eval @ webpack-internal:///./node_modules/node-pty/lib/unixTerminal.js:33
webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:17 [vue-router] Failed to resolve async component default: Error: Cannot open /Users/mmichel/Webdesign/nordvpn-electron/node_modules/node-pty/build/Release/pty.node: Error: The module '/Users/mmichel/Webdesign/nordvpn-electron/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
warn @ webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:17
webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:17 [vue-router] uncaught error during route navigation:
warn @ webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:17
webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2114 Error: Cannot open /Users/mmichel/Webdesign/nordvpn-electron/node_modules/node-pty/build/Release/pty.node: Error: The module '/Users/mmichel/Webdesign/nordvpn-electron/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.eval (webpack-internal:///./node_modules/node-pty/build/Release/pty.node:1)
    at eval (webpack-internal:///./node_modules/node-pty/build/Release/pty.node:2)
    at Object../node_modules/node-pty/build/Release/pty.node (vendor.js:2388)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (webpack-internal:///./node_modules/node-pty/lib/unixTerminal.js:26)
    at Object../node_modules/node-pty/lib/unixTerminal.js (vendor.js:2436)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (webpack-internal:///./node_modules/node-pty/lib/index.js:13)
```

**Comment by Tyriar** [comment]
@martijnmichel `node-pty-prebuilt-multiarch` is not `node-pty`

> NODE_MODULE_VERSION 79. This version of Node.js requires
> NODE_MODULE_VERSION 75. Please try re-compiling or re-installing

This means you're building with one version of node and using in another.

Closing this as if you're seeing that error it means `npm install` was not successful. See the readme for prerequisites you might be missing.

**Comment by martijnmichel** [comment]
npm install was succesful however... how do i built the correct version then?

**Comment by Un-index** [comment]
I got
NODE_MODULE_VERSION 98. This version of Node.js requires
NODE_MODULE_VERSION 99. Please try re-compiling or re-installing
.

This occurs every time I run it and it installs with 0 problems.

**Comment by Un-index** [comment]
I just noticed the example doesn't work either.

**Comment by MrJ0se** [comment]
for some rason... are npm not building automatically it for me... so i run "npm run install" in the node-pty, and rename the "build/Release" to "build/Debug", this create the pty.node, but its not working yet, now i get this...

```
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" and args undefined
[15:48:05] No ptyHost heartbeat after 6 seconds
[15:48:10] No ptyHost heartbeat after 12 seconds
```
