### ISSUE TITLE
Error during installation using npm on windows 10

### ISSUE THREAD

**Issue by chiragasawa** [microsoft/node-pty#410]
## Environment details

- OS:windows 10 pro
- OS version:1909
- node-pty version:0.9.0

## Issue description
getting the following error while installing the node-pty module of the node.js using npm according to the documentation I use the following command npm i node-pty -g my system and node version is listed following and also window build tools also install version 2017 and 2015 also npm i node-gyp -g command runs successfully.

    PS C:\Windows\system32> npm install node-pty

    > node-pty@0.9.0 install C:\Windows\system32\node_modules\node-pty
    > node scripts/install.js

    C:\Windows\system32\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\HP\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\HP\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
    MSBUILD : error MSB1009: Project file does not exist.
    Switch: build/binding.sln
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\HP\AppData\Roaming\nvm\v12.16.3\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    gyp ERR! System Windows_NT 10.0.18363
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\AppData\\Roaming\\nvm\\v12.16.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Windows\system32\node_modules\node-pty
    gyp ERR! node -v v12.16.3
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok
    npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
    npm WARN system32 No description
    npm WARN system32 No repository field.
    npm WARN system32 No README data
    npm WARN system32 No license field.

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! node-pty@0.9.0 install: `node scripts/install.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-pty@0.9.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-05-30T09_49_35_066Z-debug.log

**Comment by Tyriar** [comment]
> C:\\Users\\HP\\AppData\\Local\\node-gyp\\Cache\\12.16.3\\x64\\node.lib : fatal error LNK1127: library is corrupt [C:\Us
ers\HP\AppData\Roaming\nvm\v12.16.3\node_modules\node-pty\build\conpty.vcxproj]

I think something is wrong with your node install? I cannot reproduce myself. Try reinstalling node.js and/or the dependencies needed by the project https://github.com/microsoft/node-pty#windows
