### ISSUE TITLE
Tests fail due to glibc version issues on rasperry pi 4 with ubuntu 20.10

### ISSUE THREAD

**Issue by snoble** [microsoft/node-pty#467]
## Environment details

- OS: Ubuntu
- OS version: 20.10
- node-pty version: 0.10.0
- ldd --version: (Ubuntu GLIBC 2.32-0ubuntu3) 2.32
- uname -m: aarch64

## Issue description
`yarn test` fails with
```
Error: /snap/core/current/lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/steven/Code/node-pty/build/Release/pty.node)
```

full error:
```
steven@steven-rpi4:~/Code/node-pty$ yarn test
yarn run v1.22.10
$ cross-env NODE_ENV=test mocha -R spec --exit lib/*.test.js
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/steven/Code/node-pty/lib/unixTerminal.js
- /home/steven/Code/node-pty/lib/terminal.test.js
- /home/steven/Code/node-pty/node_modules/mocha/lib/esm-utils.js
- /home/steven/Code/node-pty/node_modules/mocha/lib/mocha.js
- /home/steven/Code/node-pty/node_modules/mocha/lib/cli/one-and-dones.js
- /home/steven/Code/node-pty/node_modules/mocha/lib/cli/options.js
- /home/steven/Code/node-pty/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/steven/Code/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/steven/Code/node-pty/lib/terminal.test.js:22:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireOrImport (/home/steven/Code/node-pty/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/home/steven/Code/node-pty/node_modules/mocha/lib/esm-utils.js:28:26)
    at async singleRun (/home/steven/Code/node-pty/node_modules/mocha/lib/cli/run-helpers.js:107:3)
    at async exports.runMocha (/home/steven/Code/node-pty/node_modules/mocha/lib/cli/run-helpers.js:144:5)
    at async Object.exports.handler (/home/steven/Code/node-pty/node_modules/mocha/lib/cli/run.js:306:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/steven/Code/node-pty/lib/unixTerminal.js',
    '/home/steven/Code/node-pty/lib/terminal.test.js',
    '/home/steven/Code/node-pty/node_modules/mocha/lib/esm-utils.js',
    '/home/steven/Code/node-pty/node_modules/mocha/lib/mocha.js',
    '/home/steven/Code/node-pty/node_modules/mocha/lib/cli/one-and-dones.js',
    '/home/steven/Code/node-pty/node_modules/mocha/lib/cli/options.js',
    '/home/steven/Code/node-pty/node_modules/mocha/bin/mocha'
  ]
}

Error: /snap/core/current/lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/steven/Code/node-pty/build/Release/pty.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/steven/Code/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/steven/Code/node-pty/lib/terminal.test.js:22:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireOrImport (/home/steven/Code/node-pty/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/home/steven/Code/node-pty/node_modules/mocha/lib/esm-utils.js:28:26)
    at async singleRun (/home/steven/Code/node-pty/node_modules/mocha/lib/cli/run-helpers.js:107:3)
    at async exports.runMocha (/home/steven/Code/node-pty/node_modules/mocha/lib/cli/run-helpers.js:144:5)
    at async Object.exports.handler (/home/steven/Code/node-pty/node_modules/mocha/lib/cli/run.js:306:5)
```

**Comment by Tyriar** [comment]
This looks like a problem with your setup, either the snap or you don't have the needed cpp tools installed.
