### ISSUE TITLE
How to send CTRL + c

### ISSUE THREAD

**Issue by frmdeveloper** [microsoft/node-pty#521]
## Environment details

- OS: Debian
- OS version: Debian 10
- node-pty version: 0.10.1

## Issue description
How to send CTRL + c
I'm confused

**Comment by Tyriar** [comment]
`pty.write('\x3')` should do it

**Comment by frmdeveloper** [comment]
``$ node``
```
root@railway:~# node
Welcome to Node.js v14.18.2.
Type ".help" for more information.
> 
```
___
``> pty.write("\x3")``
```
Execution Function:1
pty.write("\x3")
             ^
ParseError: Bad character escape sequence

SyntaxError: Invalid hexadecimal escape sequence
    at Object.exports.chatupdate (/root/frmdev/index.js:3151:54)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by 3rror404** [comment]
@frmdeveloper `pty.write("\003")` works (on MacOS at least)

**Comment by Tyriar** [comment]
My mistake, '\003', '\x03' or '\u0003' is the right syntax.
